name: Run OSV scanner on remote repo

on:
  workflow_dispatch:
    inputs: 
      repo_to_clone:
        description: 'Full name of the repo to clone (e.g. org/repo)'
        default: "iladin/dotfiles"
      scanner-args:
        description: "scanner args"
        type: string
        default: |-
          -r
          ./
      results:
        description: "name of SARIF file"
        type: string
        default: results.sarif
      upload:
        description: "Upload to Security > Code Scanning"
        type: boolean
        required: false
        default: true
      fail-on-vuln:
        description: "Whether to fail the action on vulnerability found"
        type: boolean
        default: true
jobs:
  run-osv:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.inputs.repo_to_clone }}
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          path: ./${{ github.event.inputs.repo_to_clone }}
      - name: Mkdir results-dir
      # make sure results dir is created
        run: mkdir -p ./${{ github.event.inputs.repo_to_clone }}/myResults
      - name: "Run scanner"
        uses: google/osv-scanner/actions/scanner@main
        with:
          scanner-args: |-
            --output=results.json
            --format=json
            ${{ inputs.scanner-args }}
        continue-on-error: true
      - name: "Run osv-scanner-reporter"
        uses: google/osv-scanner/actions/reporter@main
        with:
          scanner-args: |-
            --output=${{ inputs.results }}
            --new=results.json
            --gh-annotations=false
            --fail-on-vuln=${{ inputs.fail-on-vuln }}
      # Upload the results as artifacts (optional). Commenting out will disable uploads of run results in SARIF
      # format to the repository Actions tab.
      - name: "Upload artifact"
        if: "!cancelled()"
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: SARIF file
          path: ${{ inputs.results }}
          retention-days: 5
      # Upload the results to GitHub's code scanning dashboard.
      - name: "Upload to code-scanning"
        if: "${{ !cancelled() && inputs.upload == true }}"
        uses: github/codeql-action/upload-sarif@28deaeda66b76a05916b6923827895f2b14ab387 # v3.28.16
        with:
          sarif_file: ${{ inputs.results }}